# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://zekeriyaay.com/"
languageCode = "en"
defaultContentLanguage = "tr"
theme = "congo"

title = "Zekeriya AY"
copyright = "*The content on this site is licensed under a **<a class='hover:underline hover:underline-primary-300 hover:text-primary-400' href='https://creativecommons.org/licenses/by-sa/4.0/' target='_blank'>CC-BY-SA 4.0 License</a>**. The **<a class='hover:underline hover:underline-primary-300 hover:text-primary-400' href='https://github.com/ZekeriyaAY/zekeriyaay.com' target='_blank'>source code for this site</a>** is licensed under a **<a class='hover:underline hover:underline-primary-300 hover:text-primary-400' href='https://github.com/ZekeriyaAY/zekeriyaay.com/blob/main/LICENSE' target='_blank'>GPLv3</a>***."

googleAnalytics = "G-BE5REZ94JB"

enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

summaryLength = 0

disableKinds = ['taxonomy', 'term']

[permalinks]
  # blog = "/:section/:slug/"
  # notes = "/:section/:slug/"
  # projects = "/:slug/"
  # about = "hakkinda"

[author]
  name = "Zekeriya AY"
  image = "img/author.jpeg"
  bio = "a computer engineering undergraduate student interested in cybersecurity"
  links = [
    { email = "mailto:zekeriya@zekeriyaay.com" },    
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/ZekeriyaAY" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/ZekeriyaAY" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/4y23k" },
  #   { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/channel/UCcg8zjG1kt-6sRfb4ajHWXQ?sub_confirmation=1" },
  ]
