# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "custom"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true
showAppearanceSwitcher = true

enableSearch = true
enableCodeCopy = true
enableGitInfo = true

mainSections = ["blog"]
robots = "all"
showScrollToTop = true

[frontmatter]
  lastmod = [':git']

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/ZekeriyaAY/zekeriyaay.com/tree/main/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  groupByYear = true

[sitemap]
  excludedKinds = ["home", "page", "section", "taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  google = "h7gOILJJqj64agda5ngOubw8aBuvlSTETcEhziwZmIk"
  # bing = ""
  # pinterest = ""
  # yandex = ""
