baseURL = 'https://zekeriyaay.com/'
languageCode = 'en'
title = 'Zekeriya AY'
author = "Zekeriya AY"

canonifyurls = true
paginate = 20
theme = "alageek"

enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

[permalinks]
blog = "/blog/:year/:month/:slug/"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true
xhtml = true

[params]
description = "I’m a cyber security specialist. Welcome to my diary."
faviconfile = "favicon/favicon.ico"
logofile = "logo.webp"
# logofile404 = "404-memoji.png"

posts_navigation = true
progressively = true
linkedin = "ZekeriyaAY"           # just username
github = "ZekeriyaAY"             # full url for your profile
email = "mail@zekeriyaay.com" # email address

enableRSS = true
copyright = "© 2023 by Zekeriya AY"
copyrightUrl = "/privacy"

latestpostcount = 10

highlightjs = true
highlightjslanguages = [
    "bash",
    "csharp",
    "css",
    "diff",
    "django",
    "dockerfile",
    "golang",
    "javascript",
    "lisp",
    "nginx",
    "powershell",
    "python",
    "rust",
    "yaml",
]

[[menu.primary]]
identifier = "posts"
name = "Posts"
url = "/blog"
weight = 10

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 20

[[menu.secondary]]
identifier = "gpg"
name = "GPG"
url = "/gpg"
weight = 30

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
