title = "Zekeriya AY"
baseURL = "https://zekeriyaay.com"
languageCode = 'en-us'
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Zekeriya AY"
  description = "Cyber Security and System Administration enthusiast's personal website."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  # logo = ""  # url or path to a logo to put in the header
  lang = "en"
  umamiAnalytics = "26bf50d7-a2e0-467f-ba73-255295ab0ac7"   # add your tracking id
  lastUpdate = """
    <!-- LAST-UPDATE:START -->
19 Jun 2024  11:47:53 UTC
<!-- LAST-UPDATE:END -->
    """  # change to "Last updated" to use the last updated date
  [params.footer]
    # text = "By Olivier Roques"
    # url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "'Ubuntu Mono', monospace"
    fontFamilyHeader = "Dancing Script"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "200px"
    colorBlack = "#EEEEEE"  # used for text/white
    colorRed = "#dc3545"
    colorBackground = "#0F0F0F"
  # [[params.socialIcons]]
  #   icon = "fab fa-twitter"
  #   title = "Twitter"
  #   url = "https://twitter.com/"
  # [[params.socialIcons]]
  #   icon = "fas fa-envelope"
  #   title = "E-mail"
  #   url = "mailto:mail@example.com"
  # [[params.socialIcons]]
  #   icon = "ai ai-google-scholar"
  #   title = "Scholar"
  #   url = "https://scholar.google.com/"

[permalinks]
  "/" = "/:filename"

# [menu]
#   [[menu.main]]
#     name = "About"
#     url = "/"
#     weight = 1
#   [[menu.main]]
#     name = "Resume"
#     url = "/resume.pdf"
#     # 'pre' and 'post' hooks are available
#     # here we use an icon from Bootstrap https://icons.getbootstrap.com/
#     pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
#     weight = 2
#   [[menu.main]]
#     name = "Contact"
#     url = "/contact"
#     weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files