title = "Zekeriya AY"
baseURL = "https://zekeriyaay.com"
theme = "hugo-minimalist"
languageCode = 'en-us'
disableKinds = ["taxonomy", "term"]

[params]
  author = "Zekeriya AY"
  description = "A minimalist personal theme for Hugo."
  favicon = "favicon.ico"
  logo = "/img/logo.webp"

  [params.footer] 
    text = """<!-- LAST-UPDATE:START --><!-- LAST-UPDATE:END -->"""
    url = "https://github.com/marketplace/actions/datetime-of-workflow"

  [[params.sidebar]]
    name = "GitHub"
    icon = "fa-brands fa-github"
    link = "https://github.com/ZekeriyaAY"

  [[params.sidebar]]
    name = "Twitter"
    icon = "fab fa-twitter"
    link = "https://twitter.com/0x23k"

  [[params.sidebar]]
    name = "Email"
    icon = "fa fa-mail-bulk"
    link = "mailto:zekeriya@zekeriyaay.com"

  [[params.sidebar]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    link = "https://linkedin.com/in/ZekeriyaAY"

  [[params.sidebar]]
    name = "Youtube"
    icon = "fab fa-youtube"
    link = "https://youtube.com/@ZekeriyaAY"
    
  [[params.sidebar]]
    name = "Blog"
    icon = "fa fa-blog"
    link = "https://blog.zekeriyaay.com/"

  [[params.sidebar]]
    name = "GPG"
    icon = "fa fa-key"
    link = "https://keys.openpgp.org/search?q=0xC1998F1D1206E9C8"

  [[params.menu]]
    name = "About Me"
    # icon = "fa fa-home"
    link = "/"

  [[params.menu]]
    name = "Uses"
    # icon = "fa fa-file"
    link = "/uses"

  [[params.menu]]
    name = "Projects"
    # icon = "fa fa-file"
    link = "/projects"

  [[params.menu]]
    name = "Experiences"
    # icon = "fa fa-file"
    link = "/experiences"

  [[params.menu]]
    name = "Education"
    # icon = "fa fa-file"
    link = "/education"

  [[params.menu]]
    name = "Certificates"
    # icon = "fa fa-file"
    link = "/certificates"
