baseURL = "https://zekeriyaay.com"
title = "Zekeriya AY"
languageCode = "en-us"

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
enableEmoji = true
enableRobotsTXT = true

[params]
author = "Zekeriya AY"
description = "Zekeriya AY - Cyber Security Engineer, homelab enthusiast, and maker. Vulnerability management, self-hosted services, 3D printing, and more."
favicon = "favicon.ico"
umamiAnalytics = "26bf50d7-a2e0-467f-ba73-255295ab0ac7"

[build.buildStats]
enable = true

[markup.goldmark.renderer]
unsafe = true
