backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog/{{slug}}'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Icon', name: 'icons', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
