name: Hugo AlaGeek Theme

on:
  push:
    branches:
      - mainAlageek  # Set a branch to deploy
  workflow_dispatch: # Run workflow manually, through the Github Actions Workflow page directly

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      # - name: Update with Datetime of Workflow
      #   uses: ZekeriyaAY/workflow-date@main
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     date_format: '%d %b %Y  %H:%M:%S %Z'
      #     # timezone: 'UTC'
      #     tag: 'LAST-UPDATE'
      #     markdown_path: './config.toml'
      #     commit_branch: 'mainMinimalist'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-alageek
          publish_dir: ./public
          cname: zekeriyaay.com