# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 1,3,5"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: 
    branches: ["master", "main", "researcher-gh-pages", "congo-gh-pages", "shell-gh-pages", "jekyll"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: ZekeriyaAY
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: zekeriyaay.com
